# Generated by Django 5.2.3 on 2025-06-21 11:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_news_options_remove_news_image_alter_news_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsimage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='newsimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Текст новости'),
        ),
    ]
