# Generated by Django 5.2.3 on 2025-06-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_news_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsimage',
            options={'ordering': ['order'], 'verbose_name': 'Изображение новости', 'verbose_name_plural': 'Изображения новостей'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.RemoveField(
            model_name='newsimage',
            name='caption',
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='image',
            field=models.ImageField(upload_to='news/images/', verbose_name='Изображение'),
        ),
    ]
