# Generated by Django 5.2.3 on 2025-06-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_newsimage_options_remove_news_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='vk_group_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID группы VK'),
        ),
        migrations.AddField(
            model_name='news',
            name='vk_post_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID поста VK'),
        ),
    ]
